# Generated by Django 5.2.12 on 2026-07-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('assistant', 'Assistant'), ('patient', 'Patient'), ('clinic_admin', 'Clinic Admin'), ('super_admin', 'Super Admin')], max_length=15),
        ),
    ]
