# Generated by Django 5.2.12 on 2026-09-05 13:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0007_doctorprofile_bio_doctorprofile_clinic_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Nutrition', 'Daily Nutrition'), ('Heart Health', 'Cardiovascular & Heart'), ('Preventive Care', 'Preventive Wellness'), ('Mental Health', 'Stress & Mental Wellness'), ('Fitness', 'Fitness & Mobility'), ('Sleep', 'Sleep Hygiene & Rest'), ('Seasonal', 'Seasonal Care & Immunity')], default='Preventive Care', max_length=50)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('read_time', models.CharField(default='3 min read', max_length=20)),
                ('icon', models.CharField(default='fa-heart-pulse', max_length=50)),
                ('doctor_endorsement', models.CharField(default='Verified by Clinical Advisory Team', max_length=150)),
                ('likes_count', models.IntegerField(default=24)),
                ('published_date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(default='Routine Diagnostic', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('preparation', models.CharField(default='Fasting 10-12 hours recommended', max_length=255)),
                ('turnaround_time', models.CharField(default='Within 24 Hours', max_length=100)),
                ('sample_type', models.CharField(default='Blood (Serum)', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('is_popular', models.BooleanField(default=False)),
                ('icon', models.CharField(default='fa-vial', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child / Dependent'), ('Parent', 'Parent (Father/Mother)'), ('Sibling', 'Sibling'), ('Other', 'Other')], max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, default='O+', max_length=10)),
                ('allergies', models.CharField(blank=True, default='None', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='doctor.patients')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDoctorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('General Inquiry', 'General Inquiry'), ('Prescription Refill', 'Prescription Refill Request'), ('Follow-up Question', 'Follow-up Question'), ('Lab Results Clarification', 'Lab Results Clarification'), ('Appointment Query', 'Appointment Query')], default='General Inquiry', max_length=50)),
                ('message', models.TextField()),
                ('is_doctor_reply', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_messages', to='doctor.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='doctor.patients')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('Lab Report', 'Lab Report'), ('Prescription', 'Prescription'), ('Discharge Summary', 'Discharge Summary'), ('Scan / X-Ray', 'Scan / X-Ray'), ('Vaccination Card', 'Vaccination Card'), ('Insurance Card', 'Insurance Card'), ('Other', 'Other')], default='Lab Report', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='patient_docs/')),
                ('file_url', models.CharField(blank=True, default='', max_length=500)),
                ('notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to='doctor.patients')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=150)),
                ('dose_number', models.CharField(default='Dose 1', max_length=50)),
                ('date_administered', models.DateField(default=django.utils.timezone.now)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('administered_by', models.CharField(blank=True, default='Primary Health Center', max_length=150)),
                ('batch_number', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Scheduled', 'Scheduled'), ('Overdue', 'Overdue')], default='Completed', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='doctor.patients')),
            ],
        ),
    ]
