# Generated by Django 5.2.12 on 2026-07-23 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
        ('doctor', '0002_patients_user_alter_medicalrecord_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_assistants', to='doctor.clinic'),
        ),
        migrations.AddField(
            model_name='assistantprofile',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='multi_assistants', to='doctor.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='assistantprofile',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistants', to='doctor.doctorprofile'),
        ),
    ]
