# Generated by Django 5.2.12 on 2026-07-23 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='details',
            field=models.CharField(help_text='Clinical notes - visible to doctor and assistant only', max_length=2000),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='prescription',
            field=models.CharField(blank=True, default='', help_text='Visible to patient', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='remarks',
            field=models.CharField(blank=True, default='', help_text='Visible to patient', max_length=1000),
        ),
        migrations.AlterField(
            model_name='patients',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patients', to='doctor.doctorprofile'),
        ),
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('phone_number', models.CharField(blank=True, default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_clinics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointments',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.clinic'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='doctor.clinic'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.clinic'),
        ),
        migrations.AddField(
            model_name='patients',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clinic_patients', to='doctor.clinic'),
        ),
    ]
