# Generated by Django 5.2.12 on 2026-07-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_patients_user_alter_medicalrecord_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='logo',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
