# Generated by Django 5.2.12 on 2026-09-05 12:56

import doctor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_leadentry_smslog_triageescalationlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginvoice',
            name='invoice_id',
            field=models.CharField(default=doctor.models.generate_short_uuid, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='laborderticket',
            name='ticket_id',
            field=models.CharField(default=doctor.models.generate_short_uuid, max_length=30, unique=True),
        ),
    ]
