# Generated by Django 5.2.12 on 2026-09-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_billinginvoice_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='bio',
            field=models.TextField(blank=True, default='Dedicated healthcare professional specializing in comprehensive patient diagnostics, preventive wellness, and evidence-based clinical treatment.'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_address',
            field=models.CharField(blank=True, default='Sunrise Health Plaza, Pune', max_length=255),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experience_years',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.9, max_digits=3),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='review_count',
            field=models.IntegerField(default=124),
        ),
        migrations.AddField(
            model_name='patients',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='patients',
            name='blood_group',
            field=models.CharField(blank=True, default='O+', max_length=10),
        ),
        migrations.AddField(
            model_name='patients',
            name='emergency_contact_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='patients',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patients',
            name='notify_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='notify_sms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='notify_whatsapp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='preferred_language',
            field=models.CharField(default='English', max_length=30),
        ),
    ]
